[build]
  functions = 'src/functions'
  publish = 'dist'

[dev]
  command = "npm run dev"
  publish = "dist"
  port = 8888
  targetPort = 5555
  framework = '#custom'

[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/:splat'
  status = 200